# /**
#  * This file is part of oc_snowtricks project
#  *
#  * @author: SÃ©bastien CHOMY <sebastien.chomy@gmail.com>
#  * @since 2018/02
#  */

services:
  ## Autowiring
    #
    Ood\PictureBundle\:
        resource: '%kernel.project_dir%/src/Ood/PictureBundle/*'
